repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8==4.0.1',
          'flake8-builtins==1.5.3',
          'flake8-bugbear==20.1.1',
        ]
        args: [--config, .flake8]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-lll]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
      - id: mypy
        additional_dependencies: [
            types-aiofiles,
            types-mock,
        ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml, --filter-files]
  - repo: local
    hooks:
      - id: commitizen-branch
        name: commitizen conditionally check branch
        description: >
          Commitizen fails when there are no new commits. To overcome this, we created
          tiny wrapper that verifies there are commits to check.

          Original description from Commitizen:
          Check all commit messages that are already on the current branch but not the
          default branch on the origin repository. Useful for checking messages after
          the fact (e.g., pre-push or in CI) without an expensive check of the entire
          repository history.
        entry: ./conditional-commitizen.sh
        always_run: true
        language: python
        minimum_pre_commit_version: "1.4.3"
        additional_dependencies: [
          'commitizen',
        ]
