---
conditions: v1

stages:
  - name: test
  - name: deploy
    if: tag IS present

sudo: required
dist: xenial
language: python

branches:
  only:
  - main
  - /^v\d+\.\d+\.\d+$/

cache: pip
jobs:
  fast_finish: true
  include:
    - python: 3.9
      env: TOXENV=linting TOXCFG=tox.ini
      stage: test

    - python: 3.9
      env: TOXENV=py39 TOXCFG=tox.ini
      stage: test

    - python: 3.8
      env: TOXENV=py38 TOXCFG=tox.ini
      stage: test

    #- python: 3.7
      #env: TOXENV=py37 TOXCFG=tox.ini
      #stage: test


# Hotfix: setuptools is capped at version 59, as newer versions seem to have issues with importlib_metadata in python 3.7.
# See e.g. https://app.travis-ci.com/github/rossumai/rossum/jobs/560023987
install:
  - pip install tox-travis "setuptools<60" --upgrade
  - pip install .[tests]

# command to run tests
script:
  - tox -c ${TOXCFG}
