[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = [
  "."
]

[tool.black]
line-length = 100
target-version = ["py37"]
include = '\.pyi?$'
