[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rossum_ng"
version = "1.0.0"
license = {text = "MIT"}
readme = "README.md"
dependencies =[
    "aiofiles==0.8.0",
    "httpx==0.23.0"
]

[project.optional-dependencies]
tests=[
  "codecov",
  "mock==4.0.3", # Needed for Python 3.7  because unittest.mock there doesn't support AsyncMock,
  "pytest==7.1.0",
  "pytest-asyncio==0.18.3",
  "pytest-httpx==0.21.0",
  "pytest-cov==3.0.0",
  "types-aiofiles==0.8.8"
]

[tools.setuptools]
include-package-data=true
packages=["find"]

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = [
  "."
]

[tool.black]
line-length = 100
target-version = ["py37"]
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100
ensure_newline_before_comments = true
